export type ContentMode =
  | 'scale-to-fill'
  | 'scale-aspect-fit'
  | 'scale-aspect-fill'
  | 'redraw'
  | 'center'
  | 'top'
  | 'bottom'
  | 'left'
  | 'right'
  | 'top-left'
  | 'top-right'
  | 'bottom-left'
  | 'bottom-right'
